---
- name: Deploy Skydive Demo
  hosts: localhost
  gather_facts: false
  vars_files: ~/vars.yml
  tasks:
  - name: Deploy analyzer instance
    os_server:
      state: "{{ state }}"
      name: "{{ item }}"
      image: "{{ analyzer_image_name }}"
      key_name: "{{ key_name }}"
      wait: "{{ analyzer_wait }}"
      flavor: "{{ analyzer_flavor_name }}"
      auto_floating_ip: yes
      network: "{{ network_name }}"
    with_items:
      - analyzer.demo.lab.local

  - os_server_facts:
      server: analyzer.demo.lab.local
  - debug:
      var: openstack_servers
      
      
  - name: Deploy an instance
    os_server:
      state: "{{ state }}"
      name: "agent-{{ item }}.demo.lab.local"
      image: "{{ agent_image_name }}"
      key_name: "{{ key_name }}"
      wait: "{{ agent_wait }}"
      flavor: "{{ agent_flavor_name }}"
      auto_floating_ip: no
      network: "{{ network_name }}"
      userdata: |
                #!/bin/bash
                cat << EOF> /etc/skydive-agent.yml
                analyzers:
                - {{ openstack_servers.0.interface_ip }}:8082

                agent:
                  # address and port for the agent API, Format: addr:port.
                  # Default addr is 127.0.0.1
                  listen: 0.0.0.0:8081


                  topology:
                    # Probes used to capture topology information like interfaces,
                    # bridges, namespaces, etc...
                    # Available: ovsdb, docker, neutron, opencontrail, socketinfo, lxd, lldp
                    probes:
                       - lldp
                    lldp:
                      # Interfaces to listen for LLDP frames. If no list is specified,
                      # use all interfaces
                EOF
                systemctl restart skydive-agent
    with_sequence: start=1 end="{{ agent_count }}"

      
