- name: Create private operator network
  os_network:
    state: present
    name: private
    external: false

- name: Create private facing subnet
  os_subnet:
    state: present
    network_name: private
    name: private-subnet
    cidr: 172.16.123.0/24
    enable_dhcp: true
    dns_nameservers:
       - "{{ ansible_dns.nameservers.0 }}"

- name: Create tenant router
  os_router:
    state: present
    name: operator_rtr
    project: operator
    interfaces: private-subnet
    network: public
