---
- name: Add Floating IP's to all the servers
  hosts: localhost
  gather_facts: false
  tasks:
  
  - name: Create private operator network
    os_network:
      state: present
      name: demo
      external: false
      
  - name: Create private facing subnet
    os_subnet:
      state: present
      network_name: demo
      name: demo-subnet
      cidr: 172.16.125.0/24
      enable_dhcp: true
      dns_nameservers: 
        - 10.0.0.1

  - name: Create tenant router
    os_router:
      state: present
      name: demo_rtr
      project: demo
      interfaces: demo-subnet
      network: public
