- name: Update quota for operator project
  os_quota:
    name: operator
    backup_gigabytes: -1
    backups: -1
    cores: -1
    fixed_ips: -1
    floating_ips: -1
    floatingip: -1
    gigabytes: -1
    injected_file_size: -1
    injected_files: -1
    injected_path_size: -1
    instances: -1
    key_pairs: -1
    loadbalancer: -1
    per_volume_gigabytes: -1
    pool: -1
    port: -1
    properties: -1
    ram: -1
    security_group_rule: -1
    security_group: -1
    server_group_members: -1
    server_groups: -1
    snapshots: -1
    volumes: -1
    network: -1
    router: -1
    subnet: -1

